// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_XI1km4SpPfajoQgHFq5Xm0GtVxPIwtU',
    appId: '1:951988090266:web:b51d45df6f002bb2d23623',
    messagingSenderId: '951988090266',
    projectId: 'civic-fix-82a79',
    authDomain: 'civic-fix-82a79.firebaseapp.com',
    storageBucket: 'civic-fix-82a79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0SboA954z56uaTfXterTRACTbOqklKxI',
    appId: '1:951988090266:android:88619fcbc732268ad23623',
    messagingSenderId: '951988090266',
    projectId: 'civic-fix-82a79',
    storageBucket: 'civic-fix-82a79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmL06tVKOt7Pciep4VG5E1tpe0Ab_gf5w',
    appId: '1:951988090266:ios:7c2d1157913870fbd23623',
    messagingSenderId: '951988090266',
    projectId: 'civic-fix-82a79',
    storageBucket: 'civic-fix-82a79.firebasestorage.app',
    iosBundleId: 'com.example.civicfic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmL06tVKOt7Pciep4VG5E1tpe0Ab_gf5w',
    appId: '1:951988090266:ios:7c2d1157913870fbd23623',
    messagingSenderId: '951988090266',
    projectId: 'civic-fix-82a79',
    storageBucket: 'civic-fix-82a79.firebasestorage.app',
    iosBundleId: 'com.example.civicfic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_XI1km4SpPfajoQgHFq5Xm0GtVxPIwtU',
    appId: '1:951988090266:web:80a40d43cd45bf46d23623',
    messagingSenderId: '951988090266',
    projectId: 'civic-fix-82a79',
    authDomain: 'civic-fix-82a79.firebaseapp.com',
    storageBucket: 'civic-fix-82a79.firebasestorage.app',
  );
}
