// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCssF5L66VInTLvdnZ-V3MOcOQkQVRNkm0',
    appId: '1:810969059115:web:6bad2652df99232dd93f6e',
    messagingSenderId: '810969059115',
    projectId: 'civic-2cf5a',
    authDomain: 'civic-2cf5a.firebaseapp.com',
    storageBucket: 'civic-2cf5a.firebasestorage.app',
    measurementId: 'G-028ZLG1CJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1vs-aJ9Ze9VlVIRS4wnxS5hEiNNuFd8',
    appId: '1:810969059115:android:fc8e8159b2fa1c9bd93f6e',
    messagingSenderId: '810969059115',
    projectId: 'civic-2cf5a',
    storageBucket: 'civic-2cf5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQcdqm7JMAzOE29g3nD2_Hx67U-S6XZk4',
    appId: '1:810969059115:ios:38ed232177b056edd93f6e',
    messagingSenderId: '810969059115',
    projectId: 'civic-2cf5a',
    storageBucket: 'civic-2cf5a.firebasestorage.app',
    iosBundleId: 'com.example.civicfic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQcdqm7JMAzOE29g3nD2_Hx67U-S6XZk4',
    appId: '1:810969059115:ios:38ed232177b056edd93f6e',
    messagingSenderId: '810969059115',
    projectId: 'civic-2cf5a',
    storageBucket: 'civic-2cf5a.firebasestorage.app',
    iosBundleId: 'com.example.civicfic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCssF5L66VInTLvdnZ-V3MOcOQkQVRNkm0',
    appId: '1:810969059115:web:c050f0e017b8d67ed93f6e',
    messagingSenderId: '810969059115',
    projectId: 'civic-2cf5a',
    authDomain: 'civic-2cf5a.firebaseapp.com',
    storageBucket: 'civic-2cf5a.firebasestorage.app',
    measurementId: 'G-1GWCWF875G',
  );
}
